import NextTopLoader from "nextjs-toploader";
import { Inter } from "next/font/google";
import { Providers } from "@/components/Providers";
import "bootstrap/dist/css/bootstrap.min.css";
// import ImportBsJS from "src/app/global.js";
import Sidebar from "@/components/Sidebar";
import BFooter from "@/components/BFooter";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: 'InsAIghtful',
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="dark">
      {" "}
      {/*for overall make website in darkmode use-(data-bs-theme="dark")*/}
      <body className={inter.className}>
        <Providers>
          <NextTopLoader color="#f09042" showSpinner={false} speed={200} />
          <Sidebar />
          {/* <ImportBsJS /> */}
          <session />
          {children}
          <BFooter />
          {/*if global js stopped working then you can use online script link to enable overall js */}
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossOrigin="anonymous"></script>
        </Providers>
      </body>
    </html>
  );
}
