// import 'bootstrap/dist/js/bootstrap.min.js';
import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";
import "bootstrap/dist/css/bootstrap.min.css";
import ImportBsJS from "src/app/global.js";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="dark" > 
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <ImportBsJS/>
          <session />
          {children}
          {/* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> */}
        </Providers>
      </body>
    </html>
  );
}
//for overall make website in darkmode
// data-bs-theme="dark"

